---
title: "Accuracy and Precision of Continuous Non-Invasive Arterial Pressure Monitoring Compared with Invasive or Non-Invasive Blood Pressure Monitoring"
description: |
  A Systematic Review and Meta-analysis
author:
  - name: Navpreet Kamboj
    affiliation: Lawrence S. Bloomberg Faculty of Nursing, University of Toronto
    affiliation_url: https://bloomberg.nursing.utoronto.ca/
  - name: Aaron Conway
    url: https://www.aaronconway.info
    affiliation: Lawrence S. Bloomberg Faculty of Nursing, University of Toronto
    affiliation_url: https://bloomberg.nursing.utoronto.ca/
date: "`r Sys.Date()`"
output: distill::distill_article
---

<div class="l-page-outset">
<blockquote>

### Abstract

Arterial blood pressure monitoring is vital to clinical decision making. Both the gold standard for monitoring, which is invasive arterial pressure measurement, and the most common modality of blood pressure modality, non-invasive blood pressure monitoring present with limitations that can be resolved with continuous non-invasive arterial pressure (CNAP) monitoring. The objective of this systematic review is to summarize the evidence regarding the concordance between CNAP and invasive arterial pressure monitoring. Medline and EMBASE will be searched for studies published using commercially available CNAP monitoring systems that reported on a measurement of the invasive or non-invasive arterial pressure that coincided with a measurement of CNAP. Study selection and quality assessment (using the QUADAS-2) will be performed independently by two reviewers. The GRADE approach was used to summarize the strength of the body of evidence. A synthesis of the existing evidence regarding the concordance between continuous non-invasive, invasive, and non-invasive arterial pressure measurements will assist clinicians by providing them with estimates about what should be expected from these devices in critical care settings. In addition, gaps in the evidence will be identified, which will need to be addressed in further research.

### Introduction

### Methods

### Results

### Discussion

### Conclusion