---
title: "Untitled"
description: |
  A new article created using the Distill format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Distill is a publication format for scientific and technical writing, native to the web. 

Learn more about using Distill for R Markdown at <https://rstudio.github.io/distill>.

**A protocol for a systematic review of the concordance between**  **continuous non-invasive and invasive arterial pressure monitoring**

**Abstract**

**Background**

Continuous non-invasive arterial pressure (CNAP) monitoring was introduced to substitute for the gold standard for arterial pressure assessment, which is invasive arterial pressure (IAP) measurement. The usefulness of CNAP monitoring in clinical practice is based on its sensitivity, specificity and limits of agreement both for detecting hemodynamic instability and changes in arterial pressure over time. The objective of this review is to summarise the evidence regarding the concordance between CNAP and invasive arterial pressure.

**Methods/Design**

**Discussion**

## Systematic review registration This review will be registered with PROSPERO after peer review of the protocol is completed.

## Keywords:

CNAP,



**Background**

Continuous non-invasive arterial pressure (CNAP) monitoring was introduced to substitute for the gold standard for arterial pressure assessment, which is invasive arterial pressure (IAP) measurement. The usefulness of CNAP monitoring in clinical practice is based on its sensitivity, specificity and limits of agreement both for detecting hemodynamic instability and changes in arterial pressure over time. The objective of this review is to summarise the evidence regarding the concordance between CNAP and invasive arterial pressure monitoring.

Haemodynamic monitoring is a requirement for every patient in emergency
#
[ANNOTATION:

BY &#39;Navpreet Kamboj&#39;
ON &#39;2019-10-06T17:50:00&#39;NK
NOTE: &#39;Hahn 2012&#39;]
and intensive care medicine, in the operating theatre, during the postoperative period, and during interventions with distinct haemodynamic changes.1 While oxygen saturation and heart rate are measured continuously, blood pressure is usually assessed non-invasively by intermittent oscillometric measurement every 3–10 min.The first devices for the measurement of the arterial pressure waveform at the finger, based on the principle of arterial wall unloading developed by Penaz,2 were introduced in the early 1980s. In 2007, a new device for continuous non-invasive blood pressure (NIBP) measurement, which can be connected to a standard Draeger monitor, was released (InfinityTM CNAPTM SmartPodTM, CNSystems Medizintechnik AG, Graz, Austria). Recently, a studyevaluated the CNAPTM pod (Software version 2.9.14) connected to a Draeger Infinity DeltaTM monitor (Draeger Medical Systems, Inc., Danvers, MA, USA) with promising results.4 A stand-alone monitor (CNAPTM Monitor 500) with improved software (V3.0) is also now available

In patients undergoing high-risk surgery and/or presenting with major comorbidities, invasive arterial pressure monitoring is often used as the standard of care.

The goal of the continuous noninvasive arterial pressure monitoring devices is to bridge the gap between noninvasive but intermittent and continuous but invasive arterial pressure measurements. Invasive arterial pressure monitoring is associated with mechanical, infectious, and thrombotic complications.Continuous noninvasive arterial pressure monitoring devices display real-time, continuous arterial pressure waveforms and allow noninvasive beat-to-beat arterial pressure measurement. The main advantage of these technologies is that they can bridge the gap between noninvasive but intermittent oscillometric techniques and continuous but invasive arterial pressure monitoring.



**Objectives**

The objective of this systematic review is to summarise the evidence regarding the concordance between CNAP monitoring and invasive arterial pressure monitoring in order to:

- Examine the extent to which CNAP monitoring and invasive arterial pressure differ;
- Determine the ability of CNAP monitors to track changes in arterial pressure over time (i.e. trending ability); and
- Determine whether measurements from CNAP monitoring can be used to classify people into categories that are clinically meaningful

**Methods/Design**

A systematic review adhering to the protocol outlined below will be conducted. Differences between this protocol and the review will be reported.

**Criteria for considering studies for this review**

_Types of studies_

Studies conducted prior to the year 2000 will be excluded as they evaluated out-dated technology, which is not relevant to current clinical practice.

-Type of device being used (

_Types of participants_

Studies that included human participants, either volunteers or patients receiving healthcare in a clinical setting, will be included.  Although there is an on-going review focused on continuous non-invasive arterial pressure monitoring in critical care settings, studies that focused on this population will still be included.

_Types of index tests_

Studies that measured arterial pressure using CNAP and invasive arterial pressure monitoring will be included.

_Type of reference tests_

Studies that reported on a measurement of the arterial pressure using invasive arterial pressure monitoring that coincided with a measurement of the index test will be included.

_Types of outcome measures_

- Sensitivity and specificity for measurement of arterial pressure (using cut-offs defined by authors of the original study)
- Receiver operating characteristic curve analyses
- True/false negatives and true/false positives
- Difference versus average analyses reporting the mean bias, standard deviation of bias and 95% limits of agreement (otherwise referred to as Bland-Altman level of agreement or plots)
- Outcomes to evaluate trending ability (such as four-quadrant (4Q) concordance, polar plot analysis or clinical concordance).

**Search methods for identification**  **of studies**

Published studies will be identified by searching Medline and EMBASE from January 2000 as well as the reference lists of articles identified to be relevant to the review. This search strategy is an efficient approach for systematic reviews of diagnostic test accuracy studies. Unpublished and ongoing studies will be located by searching the International Clinical Trials Platform. Published conference abstracts will be included if there is sufficient detail reported to assess study quality. Language restrictions will not be imposed. The Cochrane recommended search strategy combining terms for the &#39;target condition&#39; and &#39;index test&#39; will be used. The specific search strategy for each database is presented in the appendices. In addition, we searched for other studies included in online repositories of studies that are available on the CNAP monitoring manufacturer websites.

**Data collection and analysis**

_Selection of studies_

_Data extraction and management_

_Assessment of risk of bias in included studies_

_Publication bias_

Multiple databases and an international clinical trial registry will be thoroughly searched to minimize publication bias. Obtaining data from unpublished work will be attempted and there will be no language restriction in order to reduce the risk of reporting bias.

_Data synthesis_

_Discussion_

**Abbreviations used**

_CNAP_

_AP_

**Declarations**

**Competing interests**

None for all authors

**Authors&#39; contributions**

**Acknowledgements**

No specific funding has been received for this systematic review.

**References**

