---
title: "Covidence export test"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(knitr)
```

## Load data

```{r}
data <- read_csv(here::here("covidence/cnap.csv"))
```

## Replace spaces in variable names with underscores

```{r}
data  <- janitor::clean_names(data)
```

## Convert selection of outcome variables into a long dataframe

```{r}
bp <- data %>% 
  mutate(study = study_identifier) %>% 
  select(study, 
         starts_with("sbp"), 
         starts_with("dbp"),
         starts_with("map")) %>% 
  pivot_longer(cols = -study,
               names_to = c("outcome", "cnap", "type","location", "group", "measure"),
               names_sep = "_",
                values_to = "value")  %>% 
  drop_na(value)
bp  %>% kable()
```

## Convert selection of variables with summaries of participant characteristics into a long dataframe

```{r}
summary <- data %>% 
  mutate(study = study_identifier) %>% 
  select(study, 
         starts_with("baseline"))
  
names(summary) <- str_replace(names(summary), "baseline_", "")

# need the same number of components in all the variables names to convert it to long dataframe
names(summary) <- str_replace(names(summary), "sample_", "sample_n_")

summary <- summary %>% 
  pivot_longer(cols = -study,
               names_to = c("characteristic", "measure", "group"),
               names_sep = "_",
                values_to = "value")  %>% 
  drop_na(value)
summary  %>% kable()
```

